name: Update yaml in file

on:
  repository_dispatch:
  # INPUTS
  # newVersion: new version to update to
  # actor: name of person who initiated commit original workflow

env: 
  fileToUpdate: test.yaml

jobs:
  Update-file:
    name: Updating version to ${{ github.event.client_payload.newVersion }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code from the repository
        id: checkoutCode
        uses: actions/checkout@v2

      - name: Check out yq - portable yaml processor
        uses: mikefarah/yq@v4.11.2

      - name: Use yq to update file
        run: | 
          sleep 15
          yq eval '.spec.containerTag = "${{ github.event.client_payload.newVersion }}"' --inplace ${{ env.fileToUpdate }}

      - name: Show file content
        run: |
          cat ${{ env.fileToUpdate }}

      - name: Update version to ${{ github.event.inputs.newVersion }} in file
        run: |
          git config user.name "${{ github.event.client_payload.actor }}"
          git config user.email "<>"
          git add .
          git commit -m "Update version to ${{ github.event.client_payload.newVersion }} in ${{ env.fileToUpdate }}"
          git push origin main