name: Update yaml in file

on:
  repository_dispatch:
  # INPUTS
  # actor: name of person who initiated commit original workflow
  # applicationName: name of application
  # applicationVersion: new version to update to
  # targetEnvironment: nonprod or prod

env: 
  fileToUpdate: test.yaml

jobs:
  set-up:
    name: Set up variables
    runs-on: ubuntu-latest
    outputs:
      webappPath: ${{ steps.getPath.outputs.webapp }}
    steps:
      - name: Checkout Code from the repository
        uses: actions/checkout@v2

      - name: Echo inputs
        run: |
          echo "INFO: actor=${{ github.event.client_payload.actor }}"
          echo "INFO: applicationName=${{ github.event.client_payload.applicationName }}"
          echo "INFO: applicationVersion=${{ github.event.client_payload.applicationVersion }}"
          echo "INFO: targetEnvironment=${{ github.event.client_payload.targetEnvironment }}"

      - name: Set up path to ${{ env.fileToUpdate }}
        id: getPath
        run: |
          APPNAME=$(echo "${{ github.event.client_payload.applicationName }}" | tr _ -)
          echo "::set-output name=webapp::${APPNAME}/${{ github.event.client_payload.targetEnvironment }}"

  update-file:
    name: Updating version to ${{ github.event.client_payload.applicationVersion }}
    runs-on: ubuntu-latest
    needs: set-up
    steps: 
      - name: Checkout Code from the repository
        uses: actions/checkout@v2

      - name: Check out yq - portable yaml processor
        uses: mikefarah/yq@v4.11.2

      - name: Update containerTag in ${{ needs.set-up.outputs.webappPath }}/${{ env.fileToUpdate }}
        working-directory: ${{ needs.set-up.outputs.webappPath }}
        run: | 
          yq eval '.spec.containerTag = "${{ github.event.client_payload.applicationVersion }}"' --inplace ${{ env.fileToUpdate }}

      - name: Show file content
        run: |
          cat ${{ env.fileToUpdate }}

      - name: Update version to ${{ github.event.inputs.applicationVersion }} in file
        run: |
          git config user.name "${{ github.event.client_payload.actor }}"
          git config user.email "<>"
          git add .
          git commit -m "Update version to ${{ github.event.client_payload.applicationVersion }} in ${{ env.fileToUpdate }}"
          git push origin main